name: Workflow1

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  GetLatest:
     runs-on: ubuntu-latest
     steps:
       - name: Workflow1
         run: echo "This works"
         shell: bash